### ISSUE TITLE
[Bug] NoNitroUpsell plugin breaks nitrothemes

### ISSUE THREAD

**Issue by coolesding** [Equicord/Equicord#1]
### Discord Account

coolesding

### What happens when the bug or crash occurs?

Hey cuties, i'm back on equicord

with nonitroupsell and the nitro theme plugin activated, when trying to activate a nitro theme (e.g. Strawberry Lemonade) it simply deactivates again

### What is the expected behaviour?

It should stay on

### How do you recreate this bug or crash?

you heard me right

### Errors

```
Replace this text with your crash-log.
```
im not using discord stable btw

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by thororen1234** [comment]
looking into it (didn't get notified by github till now)

**Comment by thororen1234** [comment]
seems to be fixed now.
