### ISSUE TITLE
Jumpscare plugin incorrect credit

### ISSUE THREAD

**Issue by chloecinders** [Equicord/Equicord#32]
### Content

I've just noticed that the Jumpscare plugin is credited as made by Joona. I'm not sure who Joona is but this plugin was made by me, as the plugin source clearly says.
https://github.com/Equicord/Equicord/commit/ef0810f5b19ad92b9ae96fa63962d996df4da4f5

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by KrystalSkullOfficial** [comment]
Sorry about that, our apology this must have been a typo on one of our parts.

**Comment by KrystalSkullOfficial** [comment]
this as been fix on dev, soon will be pushed to main
https://github.com/Equicord/Equicord/commit/11a32888f38a4ee3c451a563d9e002414d18522a

**Comment by thororen1234** [comment]
@surgedevs my fault I read the same plugin twice when reading authors I was looking at joonas and I didn't realize it was too far down.
