### ISSUE TITLE
[Bug] Installer Cannot Open on Windows Server 2022 VM

### ISSUE THREAD

**Issue by ptraced** [Equicord/Equicord#34]
### What happens when the bug or crash occurs?

Running Installer

### What is the expected behaviour?

The Installer Opens

### How do you recreate this bug or crash?

1. Create Windows Server 2022 VM
2. Open Equicord Installer
3. Nothing Opens

### Errors

None even check Event Viewer

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by KrystalSkullOfficial** [comment]
Um... Idk what to say, this is kinda of a known issue so use a normal version of Windows

![FromSuncordServer](https://cdn.nest.rip/uploads/69853627-a513-4d43-a168-13284ea1cb65.png)

**Comment by vMohammad24** [comment]
CLI works fine
![63](https://github.com/user-attachments/assets/cd8f3b32-1779-44c8-addd-b4daa2175c3e)

**Comment by thororen1234** [comment]
This isn't an issue on cli. GUI won't run without proper driver's and such install I would believe but cli works fine and as intended as said above

Cli link: https://github.com/Equicord/Equilotl/releases/latest/download/EquilotlCli.exe
