### ISSUE TITLE
[Bug] my fucking discord keeps crashing because I enabled status picker and it wont fucking stop.

### ISSUE THREAD

**Issue by 2bap** [Equicord/Equicord#65]
### What happens when the bug or crash occurs?

I enabled status picker and now my discord crashes upon startup.

### What is the expected behaviour?

I expected it to not fucking crash my discord 24/7

### How do you recreate this bug or crash?

1. Enable status picker
2. restart discord

### Errors

Too much shit appears

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by KrystalSkullOfficial** [comment]
please use our support channel in our discord server so we can debug this problem
https://discord.gg/bFp57wxCkv
