### ISSUE TITLE
[Bug] crash 

### ISSUE THREAD

**Issue by ghost** [Equicord/Equicord#80]
### Discord Account

qm0d7

### What happens when the bug or crash occurs?

i tried to send a 10 hour clip using the voice messages plugin and it makes the progress bar for it then crashes.
i cant join the discord for some odd reason it tells me unable to accpet invite my account is from 2017.

### What is the expected behaviour?

i expected to see the clip in chat cause the voice plugin made a progress bar for it
![image](https://github.com/user-attachments/assets/44ccc947-c089-498e-9746-75c054e9f7a0)

### How do you recreate this bug or crash?

1) upload a large audio file with the voice messages plugin
2) hit send
3) discord crashes
https://youtu.be/4-XwxU0PldY here is a demonstration
### Errors

```
Uncaught (in promise)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by KrystalSkullOfficial** [comment]
Dont send a voice messages that long, discord themselves does even support them being that long
